import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { options } from "../../auth/[...nextauth]/options";

const GEMINI_API_KEY = process.env.GEMINI_API_KEY!;

export async function POST(request: Request) {
  console.log("[AI-Playlist] Start request");
  const session = await getServerSession(options);
  console.log("session from playlist route", session);
  console.log("[AI-Playlist] Session from playlist route:", session ? {
    user: session.user,
    accessToken: session.accessToken ? 'Present' : 'Missing',
  } : 'No session');

  if (!session?.user || !session.accessToken) {
    console.log("[AI-Playlist] Unauthorized");
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { moodText } = await request.json();
  console.log("[AI-Playlist] User input:", moodText);
  if (!moodText) {
    console.log("[AI-Playlist] No mood text provided");
    return NextResponse.json({ error: "Mood text is required" }, { status: 400 });
  }

  // 1. Call Gemini Flash for analysis
  const geminiPrompt = `
    Analyze the following user input and extract:
    - mood (e.g. happy, sad, energetic, nostalgic, etc.)
    - genre (e.g. pop, bollywood, rock, etc.)
    - era/decade (e.g. 90s, 2000s, etc.)
    - theme (e.g. love, party, workout, etc.)
    - up to 5 song suggestions (title and artist, preferably with Spotify popularity)
    User input: "${moodText}"
    Respond as JSON:
    {
      "mood": "...",
      "genre": "...",
      "era": "...",
      "theme": "...",
      "suggested_songs": [
        {"title": "...", "artist": "..."},
        ...
      ]
    }
  `;
  console.log("[AI-Playlist] Gemini prompt:", geminiPrompt);

  const geminiRes = await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=" + GEMINI_API_KEY, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: geminiPrompt }] }]
    }),
  });
  console.log("[AI-Playlist] Gemini API status:", geminiRes.status);
  const geminiData = await geminiRes.json();
  console.log("[AI-Playlist] Gemini API response:", geminiData);
  const geminiText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text || geminiData.candidates?.[0]?.content?.text || "";
  let aiResult;
  try {
    // Remove code block markers if present
    const cleaned = geminiText.replace(/```json|```/g, '').trim();
    aiResult = JSON.parse(cleaned);
    console.log("[AI-Playlist] Gemini AI result:", aiResult);
  } catch {
    console.log("[AI-Playlist] Gemini response parse error:", geminiText);
    return NextResponse.json({ error: "Gemini response parse error", raw: geminiText }, { status: 500 });
  }

  // 2. Search Spotify for each suggested song
  const foundTracks: { id: string, uri: string, name: string, artist: string }[] = [];
  for (const song of aiResult.suggested_songs || []) {
    const q = encodeURIComponent(`${song.title} ${song.artist}`);
    console.log("[AI-Playlist] Searching Spotify for:", song.title, "by", song.artist);
    const searchRes = await fetch(`https://api.spotify.com/v1/search?q=${q}&type=track&limit=1`, {
      headers: { Authorization: `Bearer ${session.accessToken}` }
    });
    console.log("[AI-Playlist] Spotify search status:", searchRes.status);
    const searchData = await searchRes.json();
    console.log("[AI-Playlist] Spotify search data:", searchData);
    const track = searchData.tracks?.items?.[0];
    if (track) {
      foundTracks.push({
        id: track.id,
        uri: track.uri,
        name: track.name,
        artist: track.artists.map((a: any) => a.name).join(", ")
      });
      console.log("[AI-Playlist] Found track:", track.name, "by", track.artists.map((a: any) => a.name).join(", "));
    } else {
      console.log("[AI-Playlist] No track found for:", song.title, song.artist);
    }
  }

  if (foundTracks.length === 0) {
    console.log("[AI-Playlist] No tracks found from AI suggestions", aiResult);
    return NextResponse.json({ error: "No tracks found from AI suggestions", aiResult }, { status: 404 });
  }

  // 3. Create a playlist
  console.log("[AI-Playlist] Creating playlist for user:", session.user.id);
  const playlistRes = await fetch(`https://api.spotify.com/v1/users/${session.user.id}/playlists`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${session.accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      name: `AI Playlist: ${aiResult.mood || aiResult.theme || "Your Mood"}`,
      description: `Generated by Gemini AI: ${moodText}`,
      public: false
    })
  });
  console.log("[AI-Playlist] Playlist creation status:", playlistRes.status);
  const playlistData = await playlistRes.json();
  console.log("[AI-Playlist] Playlist data:", playlistData);

  // Add error handling for playlist creation
  if (!playlistData.id) {
    console.log("[AI-Playlist] Failed to create playlist:", playlistData);
    return NextResponse.json({ error: "Failed to create playlist", details: playlistData }, { status: playlistRes.status });
  }

  // 4. Add tracks to the playlist
  console.log("[AI-Playlist] Adding tracks to playlist:", foundTracks.map(t => t.uri));
  const addTracksRes = await fetch(`https://api.spotify.com/v1/playlists/${playlistData.id}/tracks`, {
    method: "POST",
    headers: { Authorization: `Bearer ${session.accessToken}`, "Content-Type": "application/json" },
    body: JSON.stringify({ uris: foundTracks.map(t => t.uri) })
  });
  console.log("[AI-Playlist] Add tracks status:", addTracksRes.status);
  const addTracksData = await addTracksRes.json();
  console.log("[AI-Playlist] Add tracks response:", addTracksData);

  return NextResponse.json({
    playlist: {
      id: playlistData.id,
      name: playlistData.name,
      url: playlistData.external_urls.spotify,
      tracks: foundTracks
    },
    aiResult
  });
}



// 2025-07-21T21:11:21.458Z [info] [AI-Playlist] Start request
// 2025-07-21T21:11:21.475Z [info] [AI-Playlist] Session: {
//   user: {
//     name: 'Sayan',
//     email: 'sayanmajumder0002@gmail.com',
//     image: undefined
//   },
//   accessToken: 'Present'
// }
// 2025-07-21T21:11:21.478Z [info] [AI-Playlist] User input: soothing song
// 2025-07-21T21:11:21.478Z [info] [AI-Playlist] Gemini prompt: 
//     Analyze the following user input and extract:
//     - mood (e.g. happy, sad, energetic, nostalgic, etc.)
//     - genre (e.g. pop, bollywood, rock, etc.)
//     - era/decade (e.g. 90s, 2000s, etc.)
//     - theme (e.g. love, party, workout, etc.)
//     - up to 5 song suggestions (title and artist, preferably with Spotify popularity)
//     User input: "soothing song"
//     Respond as JSON:
//     {
//       "mood": "...",
//       "genre": "...",
//       "era": "...",
//       "theme": "...",
//       "suggested_songs": [
//         {"title": "...", "artist": "..."},
//         ...
//       ]
//     }
// 2025-07-21T21:11:22.795Z [info] [AI-Playlist] Gemini API status: 200
// 2025-07-21T21:11:22.799Z [info] [AI-Playlist] Gemini API response: {
//   candidates: [
//     {
//       content: [Object],
//       finishReason: 'STOP',
//       avgLogprobs: -0.04842419094509549
//     }
//   ],
//   usageMetadata: {
//     promptTokenCount: 185,
//     candidatesTokenCount: 144,
//     totalTokenCount: 329,
//     promptTokensDetails: [ [Object] ],
//     candidatesTokensDetails: [ [Object] ]
//   },
//   modelVersion: 'gemini-2.0-flash',
//   responseId: '-ax-aJjaLNWU7dcPv9bKkQs'
// }
// 2025-07-21T21:11:22.799Z [info] [AI-Playlist] Gemini AI result: {
//   mood: 'calm',
//   genre: 'acoustic',
//   era: 'any',
//   theme: 'relaxation',
//   suggested_songs: [
//     { title: 'Weightless', artist: 'Marconi Union' },
//     { title: 'Watermark', artist: 'Enya' },
//     { title: 'Nuvole Bianche', artist: 'Ludovico Einaudi' },
//     { title: 'Clair de Lune, L. 32', artist: 'Claude Debussy' },
//     { title: 'Ave Maria', artist: 'Franz Schubert' }
//   ]
// }
// 2025-07-21T21:11:22.799Z [info] [AI-Playlist] Searching Spotify for: Weightless by Marconi Union
// 2025-07-21T21:11:23.173Z [info] [AI-Playlist] Spotify search status: 200
// 2025-07-21T21:11:23.173Z [info] [AI-Playlist] Spotify search data: {
//   tracks: {
//     href: 'https://api.spotify.com/v1/search?offset=0&limit=1&query=Weightless%20Marconi%20Union&type=track&locale=*',
//     limit: 1,
//     next: 'https://api.spotify.com/v1/search?offset=1&limit=1&query=Weightless%20Marconi%20Union&type=track&locale=*',
//     offset: 0,
//     previous: null,
//     total: 1000,
//     items: [ [Object] ]
//   }
// }
// 2025-07-21T21:11:23.173Z [info] [AI-Playlist] Found track: Weightless by Marconi Union
// 2025-07-21T21:11:23.173Z [info] [AI-Playlist] Searching Spotify for: Watermark by Enya
// 2025-07-21T21:11:23.532Z [info] [AI-Playlist] Spotify search status: 200
// 2025-07-21T21:11:23.535Z [info] [AI-Playlist] Spotify search data: {
//   tracks: {
//     href: 'https://api.spotify.com/v1/search?offset=0&limit=1&query=Watermark%20Enya&type=track&locale=*',
//     limit: 1,
//     next: 'https://api.spotify.com/v1/search?offset=1&limit=1&query=Watermark%20Enya&type=track&locale=*',
//     offset: 0,
//     previous: null,
//     total: 1000,
//     items: [ [Object] ]
//   }
// }
// 2025-07-21T21:11:23.535Z [info] [AI-Playlist] Found track: Watermark - 2009 Remaster by Enya
// 2025-07-21T21:11:23.535Z [info] [AI-Playlist] Searching Spotify for: Nuvole Bianche by Ludovico Einaudi
// 2025-07-21T21:11:23.873Z [info] [AI-Playlist] Spotify search status: 200
// 2025-07-21T21:11:23.875Z [info] [AI-Playlist] Spotify search data: {
//   tracks: {
//     href: 'https://api.spotify.com/v1/search?offset=0&limit=1&query=Nuvole%20Bianche%20Ludovico%20Einaudi&type=track&locale=*',
//     limit: 1,
//     next: 'https://api.spotify.com/v1/search?offset=1&limit=1&query=Nuvole%20Bianche%20Ludovico%20Einaudi&type=track&locale=*',
//     offset: 0,
//     previous: null,
//     total: 1000,
//     items: [ [Object] ]
//   }
// }
// 2025-07-21T21:11:23.875Z [info] [AI-Playlist] Found track: Nuvole Bianche by Ludovico Einaudi
// 2025-07-21T21:11:23.875Z [info] [AI-Playlist] Searching Spotify for: Clair de Lune, L. 32 by Claude Debussy
// 2025-07-21T21:11:24.208Z [info] [AI-Playlist] Spotify search status: 200
// 2025-07-21T21:11:24.213Z [info] [AI-Playlist] Spotify search data: {
//   tracks: {
//     href: 'https://api.spotify.com/v1/search?offset=0&limit=1&query=Clair%20de%20Lune%2C%20L.%2032%20Claude%20Debussy&type=track&locale=*',
//     limit: 1,
//     next: 'https://api.spotify.com/v1/search?offset=1&limit=1&query=Clair%20de%20Lune%2C%20L.%2032%20Claude%20Debussy&type=track&locale=*',
//     offset: 0,
//     previous: null,
//     total: 1000,
//     items: [ [Object] ]
//   }
// }
// 2025-07-21T21:11:24.213Z [info] [AI-Playlist] Found track: Clair de Lune, L. 32 by Claude Debussy, Martin Jones
// 2025-07-21T21:11:24.213Z [info] [AI-Playlist] Searching Spotify for: Ave Maria by Franz Schubert
// 2025-07-21T21:11:24.551Z [info] [AI-Playlist] Spotify search status: 200
// 2025-07-21T21:11:24.555Z [info] [AI-Playlist] Spotify search data: {
//   tracks: {
//     href: 'https://api.spotify.com/v1/search?offset=0&limit=1&query=Ave%20Maria%20Franz%20Schubert&type=track&locale=*',
//     limit: 1,
//     next: 'https://api.spotify.com/v1/search?offset=1&limit=1&query=Ave%20Maria%20Franz%20Schubert&type=track&locale=*',
//     offset: 0,
//     previous: null,
//     total: 1000,
//     items: [ [Object] ]
//   }
// }
// 2025-07-21T21:11:24.555Z [info] [AI-Playlist] Found track: Ave Maria, D. 839 by Franz Schubert, Renée Fleming, Royal Philharmonic Orchestra, Andreas Delfs
// 2025-07-21T21:11:24.555Z [info] [AI-Playlist] Creating playlist for user: undefined
// 2025-07-21T21:11:24.584Z [info] [AI-Playlist] Playlist creation status: 403
// 2025-07-21T21:11:24.587Z [info] [AI-Playlist] Playlist data: {
//   error: {
//     status: 403,
//     message: 'You cannot create a playlist for another user'
//   }
// }
// 2025-07-21T21:11:24.587Z [info] [AI-Playlist] Adding tracks to playlist: [
//   'spotify:track:6kkwzB6hXLIONkEk9JciA6',
//   'spotify:track:2XkWsVewOXOhSwWCQx2tR8',
//   'spotify:track:3weNRklVDqb4Rr5MhKBR3D',
//   'spotify:track:5u5aVJKjSMJr4zesMPz7bL',
//   'spotify:track:4GnVpbnWjHFrpXjAcPHvqM'
// ]
// 2025-07-21T21:11:24.614Z [info] [AI-Playlist] Add tracks status: 400
// 2025-07-21T21:11:24.618Z [info] [AI-Playlist] Add tracks response: { error: { status: 400, message: 'Invalid base62 id' } }
// 2025-07-21T21:11:24.619Z [error] ⨯ TypeError: Cannot read properties of undefined (reading 'spotify')
//     at u (/var/task/.next/server/app/api/playlist/generate/route.js:20:2609)
//     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
//     at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
//     at async eI.execute (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
//     at async eI.handle (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
//     at async Y (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:24556)
//     at async Q.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1025)
//     at async r3.renderToResponseWithComponentsImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:507)
//     at async r3.renderPageComponent (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:4780)
//     at async r3.renderToResponseImpl (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:5363)